services:
  #Base Postgress-DAtabase for store all data about alerts, metrics, and other info
  db:
    image: postgres:15-alpine
    container_name: sentinel-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentinel_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sentinel_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  #Redis fast cache and other status info
  redis:
    image: redis:7-alpine
    container_name: sentinel-redis
    ports:
      - "6337:6379"
  #Kafka for real-time data streaming and alerting pipeline
  kafka:
    image: apache/kafka:3.9.2
    container_name: sentinel-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@sentinel-kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: '5L6g3nShT-eMCtK--X86sw'
    ports:
      - "9092:9092"

networks:
  default:
    name: sentinel-network